config/routes.rb
Rails.application.routes.draw do

  resources :upload

end

app/models/ad_url.rb
class AdUrl < ActiveRecord::Base
	mount_uploader :file, AdUploader

  validates :file, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_iframe_requests

  def allow_iframe_requests
	  response.headers.delete('X-Frame-Options')
	end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
	before_filter :allow_iframe_requests
	def new
		@ad_url = AdUrl.new
	end

	def create
		ad_url = AdUrl.new(url_params)
    ad_url.save!
    session[:ad_url] = nil
    session[:ad_url] = session[:ad_url].to_s + "http://" + request.host + "/" + ad_url.file.store_dir + "/" + ad_url.file.filename
    redirect_to new_upload_path 
	end

	private

	def url_params
    params.require(:ad_url).permit(:file)
  end

  def allow_iframe_requests
	  response.headers.delete('X-Frame-Options')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upload</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/upload/new.html.erb
<div id="wrapper" class="wat-cf">
  <div id="main">
    <div class="block" id="block-text">
      <div class="content">
        <div class="inner">
          <p class="first">
          <%= form_for @ad_url, :url => upload_index_path, :html => {:multipart => true} do |f| %>
            <div>
              <table>
                <tr>
                  <%= label_tag "選擇JS檔案"%>
                  <%= f.file_field :file %>
                </tr>
                <tr>
                  <%= f.submit("upload") %>
                </tr>
              </table>
            </div>
          <% end %>
          <p>
            <%= session[:ad_url].html_safe if session[:ad_url].present? %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>